import { Fragment, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useStore } from '../data/context';
import { CONDITIONS, type Handover, type HandoverItem, type Condition } from '../data/types';
import { PageHead, Section, Status, DataTable, Input, Select, SearchSelect, ReadOnly, Alert, useAction, fmtDate, fmtDateTime, type Column } from '../components/ui';
import { HandoverDoc, ClearanceDoc } from '../documents';
import { parseAccessories, serializeAccessories, roman } from '../lib/accessories';
import { askReason } from '../components/Dialog';

const ACK = 'I acknowledge that I have received the company assets listed above in the stated condition. I accept responsibility for their proper use, protection and return in accordance with company policy. I will immediately report any loss, damage or malfunction.';

export function HandoverList() {
  const { db, store } = useStore();
  const nav = useNavigate();
  const [filter, setFilter] = useState('');
  const [clearanceEmp, setClearanceEmp] = useState('');
  const u = store.currentUser;
  const rows = db.handovers
    .filter(h => store.can('asset.view_all') || (store.can('asset.view_department') && store.employee(h.employeeId)?.departmentId === u.departmentId) || h.employeeId === u.employeeId)
    .filter(h => !filter || h.status === filter)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const columns: Column<Handover>[] = [
    { key: 'id', header: 'Reference', render: h => <span className="mono">{h.id}</span> },
    { key: 'date', header: 'Date', render: h => fmtDate(h.date) },
    { key: 'emp', header: 'Employee', render: h => <>{store.employeeName(h.employeeId)} <span className="muted small">{store.employee(h.employeeId)?.employeeCode}</span></> },
    { key: 'dept', header: 'Department', render: h => store.deptName(store.employee(h.employeeId)?.departmentId) },
    { key: 'items', header: 'Assets', render: h => h.items.map(i => i.assetId).join(', ') },
    { key: 'purpose', header: 'Purpose', render: h => h.purpose },
    { key: 'status', header: 'Status', render: h => <Status value={h.status} /> },
  ];
  return (
    <>
      <PageHead crumbs="Custody" title="Assets Assigned to Employees" actions={<>
        {store.can('reports.view') && <SearchSelect className="tb" style={{ minWidth: 260 }} value={clearanceEmp} onChange={e => setClearanceEmp(e.target.value)} placeholder="Employee clearance report…" options={db.employees.map(e => ({ value: e.id, label: `${e.name} (${e.employeeCode})` }))} />}
        {store.can('handover.create') && <Link className="btn primary" to="/handovers/new">Assign Asset to Employee</Link>}
      </>} />
      {clearanceEmp && <ClearanceDoc employee={store.employee(clearanceEmp)!} />}
      <div className="toolbar">
        <SearchSelect className="tb" value={filter} onChange={e => setFilter(e.target.value)} placeholder="All statuses" options={['Awaiting Acknowledgement', 'Active', 'Closed', 'Rejected'].map(s => ({ value: s === 'Rejected' ? 'Rejected' : s, label: s === 'Rejected' ? 'Cancelled' : s }))} />
        <span className="muted small">{rows.length} assignments</span>
      </div>
      <Section title="Assignment Register" compact><DataTable rows={rows} columns={columns} onRowClick={h => nav(`/handovers/${h.id}`)} /></Section>
    </>
  );
}

export function HandoverDetail() {
  const { id } = useParams();
  const { db, store } = useStore();
  const { run, Messages } = useAction();
  const h = db.handovers.find(x => x.id === id);
  const [sig, setSig] = useState('');
  const [signatory, setSignatory] = useState(db.users.find(u => u.role === 'super_admin')?.id ?? '');
  const [agree, setAgree] = useState(false);
  if (!h) return <Alert kind="error">Assignment not found.</Alert>;
  const emp = store.employee(h.employeeId)!;
  const isRecipient = store.currentUser.employeeId === h.employeeId;
  const canAck = h.status === 'Awaiting Acknowledgement' && (isRecipient || store.can('handover.create'));

  return (
    <>
      <PageHead crumbs="Custody / Asset Assigned to Employee" title={h.id} actions={<Status value={h.status} />} />
      <Messages />
      {h.transferId && <Alert>This assignment was generated by transfer <Link to="/transfers">{h.transferId}</Link>. The new custodian must acknowledge before the asset becomes Assigned.</Alert>}
      <div className="grid cols-2">
        <Section title="Workflow">
          <dl className="kv">
            <dt>Created</dt><dd>{fmtDateTime(h.createdAt)} by {store.userName(h.createdByUserId)}</dd>
            <dt>Submitted by</dt><dd>{store.userName(h.approvedByUserId ?? h.createdByUserId)} · {fmtDateTime(h.approvedAt ?? h.createdAt)}{h.approvalComments && ` · “${h.approvalComments}”`}</dd>
            <dt>Acknowledgement</dt><dd>{h.acknowledged ? <>Signed “{h.employeeSignature}” · {fmtDateTime(h.acknowledgedAt)}</> : <Status value="Pending" />}</dd>
            <dt>Authorized Signatory</dt><dd>{store.userName(h.authorizedSignatoryUserId)}</dd>
          </dl>
        </Section>
        <div>
          {h.status === 'Awaiting Acknowledgement' && store.can('handover.create') && (
            <Section title="Cancel Assignment"><p className="small">Withdraws this assignment before signature and returns the reserved asset(s) to Available.</p>
              <button className="btn danger" onClick={async () => { const reason = await askReason({ title: `Cancel assignment ${h.id}`, message: 'The reserved assets will become Available again.', confirmLabel: 'Cancel assignment' }); if (reason) run(() => store.cancelHandover(h.id, reason), 'Assignment cancelled; assets released.'); }}>Cancel Assignment</button></Section>
          )}
          {canAck && (
            <Section title="Employee Acknowledgement (Rule 7)">
              <p className="small" style={{ fontStyle: 'italic' }}>“{ACK}”</p>
              <div className="form-grid cols-2">
                <Input label={`Employee signature (type full name: ${emp.name})`} required value={sig} onChange={e => setSig(e.target.value)} />
                <Select label="Authorized Signatory" value={signatory} onChange={e => setSignatory(e.target.value)} options={db.users.filter(u => ['super_admin', 'dept_head'].includes(u.role)).map(u => ({ value: u.id, label: u.name }))} />
              </div>
              <label className="checkbox" style={{ margin: '10px 0' }}><input type="checkbox" checked={agree} onChange={e => setAgree(e.target.checked)} /> I have verified the condition and accessories of each asset listed.</label>
              <button className="btn primary" disabled={!agree || !sig.trim()} onClick={() => run(() => store.acknowledgeHandover(h.id, sig, signatory), 'Assignment acknowledged. Assets are now Assigned.')}>Sign & Accept Assets</button>
            </Section>
          )}
          {h.status === 'Active' && store.can('return.create') && <Section title="Actions"><div className="btn-row">{h.items.map(i => store.asset(i.assetId)?.status === 'Assigned' && <Link key={i.assetId} className="btn" to={`/returns?asset=${i.assetId}`}>Return {i.assetId}</Link>)}</div></Section>}
        </div>
      </div>
      <HandoverDoc handover={h} />
    </>
  );
}

export function HandoverNew() {
  const { db, store } = useStore();
  const nav = useNavigate();
  const [sp] = useSearchParams();
  const { run, Messages } = useAction();
  const [employeeId, setEmployeeId] = useState('');
  const [issuedBy, setIssuedBy] = useState(store.currentUser.id);
  const reason = 'Asset assigned to employee';
  const [items, setItems] = useState<HandoverItem[]>(() => {
    const pre = sp.get('asset'); const a = pre ? store.asset(pre) : undefined;
    return a && a.status === 'Available' ? [{ assetId: a.id, condition: a.condition, quantity: 1, accessories: a.accessories ?? '', remarks: '' }] : [];
  });
  const [pick, setPick] = useState('');
  // Editable accessory rows per asset (kept in state so a new blank row can exist before it is named).
  type Acc = { name: string; model: string; qty: number };
  const [accRows, setAccRows] = useState<Record<string, Acc[]>>(() => Object.fromEntries(items.map(it => [it.assetId, parseAccessories(it.accessories)])));
  const rowsFor = (assetId: string, fallback: string) => accRows[assetId] ?? parseAccessories(fallback);
  const setRows = (i: number, assetId: string, list: Acc[]) => { setAccRows(r => ({ ...r, [assetId]: list })); upd(i, { accessories: serializeAccessories(list) }); };
  const emp = store.employee(employeeId);
  const available = db.assets.filter(a => a.status === 'Available' && !items.some(i => i.assetId === a.id));
  const add = () => { const a = store.asset(pick); if (!a) return; setItems([...items, { assetId: a.id, condition: a.condition, quantity: 1, accessories: a.accessories ?? '', remarks: '' }]); setAccRows(r => ({ ...r, [a.id]: parseAccessories(a.accessories) })); setPick(''); };
  const upd = (i: number, p: Partial<HandoverItem>) => setItems(items.map((it, j) => j === i ? { ...it, ...p } : it));

  const submit = (e: FormEvent) => {
    e.preventDefault();
    const h = run(() => store.createHandover({ employeeId, issuedByUserId: issuedBy, items, reason }));
    if (h) nav(`/handovers/${h.id}`);
  };

  return (
    <>
      <PageHead crumbs="Custody / Asset Assigned to Employee" title="Assign Asset to Employee" actions={<span className="mono muted">{store.nextRef('HO', db.handovers)}</span>} />
      <div className="rule-note">Only <b>Available</b> assets can be assigned (Rule 4). Submitting reserves the assets; they become <b>Assigned</b> once the employee signs the acknowledgement (Rule 7).</div>
      <form onSubmit={submit}>
        <Messages />
        <Section title="Employee Details">
          <div className="form-grid cols-4">
            <Select label="Employee" required span={2} value={employeeId} onChange={e => setEmployeeId(e.target.value)} placeholder="Select employee…" options={db.employees.filter(e => e.active).map(e => ({ value: e.id, label: `${e.name} — ${e.employeeCode} (${store.deptName(e.departmentId)})` }))} />
            <ReadOnly label="Employee ID" value={emp?.employeeCode ?? ''} />
            <ReadOnly label="ERP ID" value={emp?.erpId ?? ''} />
            <ReadOnly label="Designation" value={emp?.designation ?? ''} />
            <ReadOnly label="Department" value={emp ? store.deptName(emp.departmentId) : ''} />
            <ReadOnly label="Date of Joining" value={emp ? fmtDate(emp.dateOfJoining) : ''} />
            <ReadOnly label="Work Location" value={emp ? store.locName(emp.workLocationId) : ''} />
            <ReadOnly label="Mobile / Email" value={emp ? `${emp.mobile} · ${emp.email}` : ''} />
          </div>
        </Section>
        <Section title="Assignment Details">
          <div className="form-grid cols-4">
            <ReadOnly label="Assignment Reference No" value={store.nextRef('HO', db.handovers)} />
            <ReadOnly label="Assigned Date" value={fmtDate(new Date().toISOString())} />
            <Select label="Issued By" required value={issuedBy} onChange={e => setIssuedBy(e.target.value)} options={db.users.filter(u => ['asset_admin', 'super_admin'].includes(u.role)).map(u => ({ value: u.id, label: u.name }))} />
          </div>
        </Section>
        <Section title="Assets to Assign" compact className="assign-card" right={<span className="ac-count">{items.length} selected</span>}>
          <div className="assign-bar">
            <span className="ab-label">Add asset</span>
            <SearchSelect className="tb" value={pick} onChange={e => setPick(e.target.value)} placeholder={available.length ? 'Search asset ID, name or serial…' : 'No assets are Available'} options={available.map(a => ({ value: a.id, label: `${a.id} — ${a.name} (${a.serialNumber})` }))} />
            <button type="button" className="btn sm primary" disabled={!pick} onClick={add}>Add to list</button>
            <span className="ab-avail">{available.length} available</span>
          </div>
          <div className="table-wrap">
          <table className="data assign">
            <thead><tr><th className="ix">#</th><th>Asset ID / Accessories</th><th>Asset Type</th><th>Make and Model</th><th>Serial / IMEI / SIM</th><th>Condition</th><th>Qty</th><th>Remarks</th><th /></tr></thead>
            <tbody>
              {items.length === 0 && <tr><td className="empty" colSpan={9}>
                {available.length > 0
                  ? <>Pick an asset from <b>Add asset</b> above — {available.length} asset(s) are Available.</>
                  : db.assets.length === 0
                    ? <>No assets have been registered yet. <Link to="/assets/register">Register an asset</Link> or use <Link to="/assets/import">Bulk Import</Link> first.</>
                    : <>None of the {db.assets.length} registered asset(s) are <b>Available</b> to assign — {[...new Set(db.assets.map(a => a.status))].map(st => `${db.assets.filter(a => a.status === st).length} ${st}`).join(', ')}. Return or free one, or <Link to="/assets/register">register a new asset</Link>.</>}
              </td></tr>}
              {items.map((it, i) => { const a = store.asset(it.assetId)!; const acc = rowsFor(it.assetId, it.accessories);
                const setAcc = (list: Acc[]) => setRows(i, it.assetId, list);
                return (
                <Fragment key={it.assetId}>
                  <tr className="assign-main">
                    <td className="ix"><span className="ix-dot">{i + 1}</span></td>
                    <td><span className="asset-chip mono">{a.id}</span><div className="muted small">{a.name}</div></td>
                    <td>{store.catName(a.categoryId)}</td>
                    <td>{a.manufacturer} {a.model}</td>
                    <td className="mono">{[a.serialNumber, a.imei, a.sim].filter(Boolean).join(' / ') || <span className="muted">—</span>}</td>
                    <td><SearchSelect className="tb" style={{ minWidth: 118 }} value={it.condition} onChange={e => upd(i, { condition: e.target.value as Condition })} options={CONDITIONS.map(c => ({ value: c, label: c }))} /></td>
                    <td><input className="ai qty" type="number" min={1} value={it.quantity} onChange={e => upd(i, { quantity: Number(e.target.value) })} /></td>
                    <td><input className="ai" value={it.remarks} placeholder="Optional note" onChange={e => upd(i, { remarks: e.target.value })} /></td>
                    <td className="act"><button type="button" className="btn sm rm" onClick={() => setItems(items.filter((_, j) => j !== i))}>Remove</button></td>
                  </tr>
                  {acc.map((x, j) => (
                    <tr key={j} className="assign-acc">
                      <td className="ix"><span className="ix-sub">{roman(j + 1)}</span></td>
                      <td><span className="acc-tag">Accessory</span></td>
                      <td><input className="ai" value={x.name} placeholder="e.g. Charger" onChange={e => setAcc(acc.map((y, k) => k === j ? { ...y, name: e.target.value } : y))} /></td>
                      <td><input className="ai" value={x.model} placeholder="Model / details" onChange={e => setAcc(acc.map((y, k) => k === j ? { ...y, model: e.target.value } : y))} /></td>
                      <td className="dash">—</td><td className="dash">—</td>
                      <td><input className="ai qty" type="number" min={1} value={x.qty} onChange={e => setAcc(acc.map((y, k) => k === j ? { ...y, qty: Math.max(1, Number(e.target.value) || 1) } : y))} /></td>
                      <td />
                      <td className="act"><button type="button" className="btn sm rm" onClick={() => setAcc(acc.filter((_, k) => k !== j))}>Remove</button></td>
                    </tr>
                  ))}
                  <tr className="assign-add"><td /><td colSpan={8}><button type="button" className="btn sm add-acc" onClick={() => setAcc([...acc, { name: '', model: '', qty: 1 }])}>+ Add accessory</button></td></tr>
                </Fragment>); })}
            </tbody>
          </table>
          </div>
        </Section>
        <div className="btn-row end" style={{ marginBottom: 18 }}><Link className="btn ghost" to="/handovers">Cancel</Link><button className="btn primary" type="submit" disabled={!employeeId || items.length === 0}>Submit</button></div>
      </form>
    </>
  );
}
